services:
  - type: web
    name: luminapdf
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
    plan: free
    preInstallCommand: |
      apt-get update && apt-get install -y poppler-utils
